config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "rooms#index"
  resources :users, only: [:show, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
  end
  resources :rooms, only: :create do
    resources :messages, only: [:index, :create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
  end
  resources :favorites, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :message
  # 同じ投稿を複数回お気に入り登録させないため
  validates_uniqueness_of :message_id, scope: :user_id # バリデーション（ユーザーとメッセージの組み合わせ
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    image.attached?
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options on: :create do
    PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
    validates_format_of :password, with: PASSWORD_REGEX, message: 'は半角英数字混合で入力してください'
    validates :password, length: { minimum: 6 }
  end

  with_options presence: true do
    validates :nickname, length: { maximum: 8 }
    validates :first_name
    validates :last_name
  end

  has_many :messages
  has_many :favorites, dependent: :destroy
  has_many :favorite_messages, through: :favorites, source: :message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @messages = @user.messages
    @favorite_messages = @user.favorite_messages
  end

  def create
    favorite = current_user.favorites.build(message_id: params[:message_id])
    favorite.save
    redirect_to room_messages_path
  end

  def destroy
    favorite = Favorite.find_by(message_id: params[:message_id], user_id: current_user.id)
    favorite.destroy
    redirect_to room_messages_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :get_room, only: [:index, :create, :destroy]

  def index
    @message = Message.new
    get_messages
  end

  def create
    @message = @room.messages.new(messages_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      get_messages
      render :index
    end
  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
    redirect_to room_messages_path(@room)
  end

  private

  def messages_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def get_messages
    @messages = @room.messages.includes(:user)
  end

  def get_room
    @room = Room.find(params[:room_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def show
    @messages = current_user.messages
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :first_name, :last_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/show.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>My Account</h2>
      <h4><b><%= current_user.nickname %></b>のお気に入り</h4>
      <%= link_to "アカウント編集", edit_user_path(current_user), class: 'btn' %>
      <%= link_to "チャットページに戻る", root_path, class: 'btn' %>
      <%= link_to "自分のメッセージを見る", user_path(current_user), class: 'btn' %>
    </div>
    <div class='account-page__inner--right user-form'>
      <h4><b>My Favorites</b></h4>
      <div class='messages'>
        <% @favorite_messages.each do |message|  %>
          <div class='message'>
            <div class='upper-message'>
              <div class='message-user'>
                <%= message.user.nickname %>
              </div>
              <div class='message-date'>
                <%= l message.created_at %>
              </div>
            </div>
            <div class='lower-message'>
              <div class='message-content'>
                <%= message.content %>
              </div>
              <%= image_tag message.image.variant(resize: '250x250'), class: 'message-image' if message.image.attached? %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shareapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/11d6e63fb0.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    
  </div>
</div>

<div class="messages">
  <%= render partial: 'message', collection: @messages %>
  <div id="image-list"></div>
</div>

<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <%= message.user.nickname %>
    </div>
    <div class="message-date">
      <%= l message.created_at %>
    </div>
    <div class="delete-btn">
      <% if user_signed_in? && current_user.id == message.user_id %>
          <%= link_to '削除', room_message_path(@room, message.id), method: :delete %>
      <% end %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <%= message.content %>
    </div>
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
  </div>
  <div class="favorite-btn">
    <% if user_signed_in? %>
      <% if message.favorited_by?(current_user) %>
        <%= link_to room_message_favorites_path(@room, message.id), method: :delete do %>
          <i class="far fa-heart unlike-btn"></i>
        <% end %>
      <% else %>
        <%= link_to room_message_favorites_path(@room, message.id), method: :post do %>
          <i class="far fa-heart like-btn"></i>
        <% end %>
      <% end %>
    <% else %>
      <p><span>お気に入り数: </span><%= message.favorites.count %></p>
    <% end %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to current_user.nickname, user_path(current_user) %>
  </div>
</div>

<div class="rooms">
  <% Room.all.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h4>アカウントの編集</h4>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", root_path, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :nickname%>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :first_name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :first_name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :last_name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :last_name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>My Account</h2>
      <h4><b><%= current_user.nickname %></b>のマイページ</h4>
      <%= link_to "アカウント編集", edit_user_path(current_user), class: 'btn' %>
      <%= link_to "チャットページに戻る", root_path, class: 'btn' %>
      <%= link_to "お気に入りを見る", favorite_path, class: 'btn' %>
    </div>
    <div class='account-page__inner--right user-form'>
      <h4><b>My Messages</b></h4>
      <div class='messages'>
        <% @messages.each do |message|  %>
          <div class='message'>
            <div class='upper-message'>
              <div class='message-user'>
                <%= message.user.nickname %>
              </div>
              <div class='message-date'>
                <%= l message.created_at %>
              </div>
            </div>
            <div class='lower-message'>
              <div class='message-content'>
                <%= message.content %>
              </div>
              <%= image_tag message.image.variant(resize: '250x250'), class: 'message-image' if message.image.attached? %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>